version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test-frontend:
    executor: node/default
    working_directory: ~/project/frontend
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./test-results/
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm install jest-junit
      # - run:
      #     name: Run frontend tests
      #     command: npm test --ci --runInBand --reporters=default --reporters=jest-junit
      - run:
          name: Run frontend linter
          command: npm run lint
      - store_test_results:
          path: ./test-results/


    build-frontend:
    executor: node/default
    working_directory: ~/project/frontend
    environment:
      JEST_JUNIT_OUTPUT_DIR: ./build-results/
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: deploy app
          command: curl "https://api.render.com/deploy/srv-cqdomd0gph6c73aa4ddg?key=HCjL0_dIR1w"
workflows:
  test:
    jobs:
      - test-frontend\
  build:
    jobs:
      - build-frontend\
